server.port=8082
spring.application.name=transaction-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/trx_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Akbar_123}
spring.jpa.hibernate.ddl-auto=validate

service.product.url=${PRODUCT_SERVICE_URL:http://localhost:8081/api/v1/products}